apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: backend-api
        image: aravind80555/shop-backend:v15
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mern-db-secret  # The exact name of the secret we just created in GCP
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret-vault
              key: JWT_SECRET
