apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: backend-api
        image: aravind80555/shop-backend:latest
        ports:
        - containerPort: 5000
